# Generated by Django 3.2 on 2023-04-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(default='no_image.jpg', upload_to='event_images')),
                ('event_name', models.CharField(default='', max_length=150)),
                ('event_price', models.DecimalField(decimal_places=2, default='', max_digits=8)),
                ('event_date', models.CharField(default='', max_length=100)),
                ('event_time_start', models.TimeField(default='')),
                ('event_time_ends', models.TimeField(default='')),
                ('event_location', models.CharField(default='', max_length=300)),
                ('event_description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
